name: Test

# on:
  # push:
  #   branches:
  #     - "main"
 
on:
  workflow_dispatch:
   inputs:
     branch:
       description: 'Branch to run the workflow on'
       required: true
       default: 'feat-struct-refactor' # pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ["stable", "nightly"]

    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Prepare dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-neotest/nvim-nio ~/.local/share/nvim/site/pack/vendor/start/nvim-nio
          nvim --headless -c 'TSInstallSync lua | quit'

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: make test
